/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.9 at Thu Sep  4 11:30:21 2014. */

#include "authExchProto.pb.h"



const pb_field_t authExchProto_fields[6] = {
    PB_FIELD2(  1, BYTES   , REQUIRED, STATIC  , FIRST, authExchProto, msgType, msgType, 0),
    PB_FIELD2(  2, BYTES   , OPTIONAL, STATIC  , OTHER, authExchProto, data1, msgType, 0),
    PB_FIELD2(  3, BYTES   , OPTIONAL, STATIC  , OTHER, authExchProto, data2, data1, 0),
    PB_FIELD2(  4, BYTES   , OPTIONAL, STATIC  , OTHER, authExchProto, data3, data2, 0),
    PB_FIELD2(  5, BYTES   , OPTIONAL, STATIC  , OTHER, authExchProto, data4, data3, 0),
    PB_LAST_FIELD
};


